version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-jenkins-pipeline-tutorial"
s3_prefix = "github_testing"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[QA]
[QA.deploy]
[QA.deploy.parameters]
stack_name = "aws-sam-jenkins-pipeline-tutorial"
s3_prefix = "github_testing_qa"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
